#This playbook finishes an upgrade prepared with prepare-upgrade.yml

## You could simply run site.yml instead, but this contains only the steps
## needed for upgrade (and therefore should be faster).

- name: deploy seafile and apply configuration
  hosts: nodes

  roles:
    - nodes

- name: deploy seafile background node
  hosts: background

  roles:
    - bgnode
