#This playbook installs a clustersetup

# update packet cache
- hosts: all
  tasks:
  - apt:
      cache_valid_time: 3600
      update_cache: yes
  sudo: yes

- name: apply common configuration to all nodes
  hosts: all
  remote_user: ubuntu
  sudo: yes

  roles:
    - common

- name: deploy and configure memcached server
  hosts: memcached
  remote_user: ubuntu
  sudo: yes

  roles:
    - memcached

- name: deploy MySQL and configure the databases
  hosts: dbserver
  remote_user: ubuntu

  roles:
    - db

- name: deploy seafile and apply configuration
  hosts: nodes
  remote_user: ubuntu
  sudo: yes

  roles:
    - nodes
