#This Playbook contains the adjustments for the background tasks node

- name: Install openjdk
  apt: name=openjdk-7-jre state=present

- name: Install libreoffice
  apt: name=libreoffice state=present

- name: Install python3-uno 
  apt: name=python3-uno state=present

- name: Install poppler-utils (pdftotext)
  apt: name=poppler-utils state=present

# adapt seahub_settings.py
- name: Remove CONVERTOR_ROOT from seahub_settings.py
  lineinfile: dest={{ seafile_base_dir }}/seahub_settings.py state=absent regexp="^OFFICE_CONVERTOR_ROOT"
- name: Add CONVERTOR_NODE to seahub_settings.py
  lineinfile: dest={{ seafile_base_dir }}/seahub_settings.py state=present line="OFFICE_CONVERTOR_NODE = True"

# rollout background init.d script
- name: Create init.d script
  template: >
    src=init-seafile-server.j2
    dest=/etc/init.d/seafile-server
    owner=root
    group=root
    mode=0755

#rollout custom nginx config
#depends on existing nginx node rollout
- name: Configure nginx seafile conf
  template: src=seafile.j2 dest=/etc/nginx/sites-available/seafile
  notify:
  - Reload nginx

- include_vars: dbconfig.yml
- name: configure seafevents.conf
  template: src=seafevents.conf.j2 dest={{ seafile_base_dir }}/pro-data/seafevents.conf

- name: restart seafile-background-tasks
  service: name=seafile-server state=restarted
