#This Playbook contains the adjustments for the background tasks node

- name: Install openjdk
  apt: name=openjdk-7-jre state=present

- name: Install libreoffice
  apt: name=libreoffice state=present

- name: Install python3-uno 
  apt: name=python3-uno state=present

- name: configure seahub_settings.py
  template: src=seahub_settings.py.j2 dest=/data/seafile/seahub_settings.py

- name: configure seafevents.conf
  template: src=seafevents.conf.j2 dest=/data/seafile/pro-data/seafevents.conf

#TODO: restart seafile.sh, seahub.sh and start seafile-background-tasks.sh
