# clones of golden image
#
- name: "create {{ seafile_base_dir }}"
  file: name={{ seafile_base_dir }} state=directory

- name: "sync from golden image"
  synchronize: >
    src="{{ seafile_base_dir }}/" dest="{{ seafile_base_dir }}"
    rsync_path="sudo rsync"
    rsync_opts="--delete --exclude=/logs --exclude=/pids --exclude=runtime/*"
  delegate_to: "{{ groups['master'][0] }}"
