# This playbook contains the config file for the seafile nodes.

- name: Configure nginx seafile conf
  template: src=seafile.j2 dest=/etc/nginx/sites-available/seafile
  notify:
  - Reload nginx

- name: "nginx: enable seafile site"
  file: state=link src=/etc/nginx/sites-available/seafile dest=/etc/nginx/sites-enabled/seafile
  notify:
  - Reload nginx

- name: "nginx: disable default site"
  file: state=absent dest=/etc/nginx/sites-enabled/default
  notify:
  - Reload nginx

- name: "nginx: install certificate"
  copy: src={{ item }} dest=/etc/ssl/ owner=root group=root
  with_items:
    - filesync-chain.pem
    - filesync-key.pem
  notify:
  - Reload nginx

- name: "nginx: hash_bucket_size fix"
  lineinfile: dest=/etc/nginx/nginx.conf insertafter="http {" line="server_names_hash_bucket_size 64;" state=present

- name: configure memcached.conf
  template: src=memcached.conf.j2 dest=/etc/memcached.conf

- name: check ccnet dir
  file: state=directory dest=/data/seafile/ccnet mode=0600

- name: configure ccnet.conf
  template: src=ccnet.conf.j2 dest=/data/seafile/ccnet/ccnet.conf

  # mykey.peer gets generated by ccnet-init
  # rsa key used for non-http sync
- name: copy mykey.peer matching ccnet.conf id
  copy: src=mykey.peer dest=/data/seafile/ccnet/

- name: check ccnet/misc dir
  file: state=directory dest=/data/seafile/ccnet/misc

- name: copy non-http sync pubkey
  copy: src=76b8d77ea4a83b76f3c0c74ed57270bf7aef0c2a.peer dest=/data/seafile/ccnet/misc/

- name: copy basic seafile.ini
  copy: src=seafile.ini dest=/data/seafile/ccnet/

- name: configure seahub_settings.py
  template: src=seahub_settings.py.j2 dest=/data/seafile/seahub_settings.py

- name: check seafile-data dir
  file: state=directory dest=/data/seafile/seafile-data

- name: configure seafile.conf
  template: src=seafile.conf.j2 dest=/data/seafile/seafile-data/seafile.conf

- name: check conf dir
  file: state=directory dest=/data/seafile/conf

- name: copy seafdav.conf (default settings)
  copy: src=seafdav.conf dest=/data/seafile/conf/

- name: check pro-data dir
  file: state=directory dest=/data/seafile/pro-data

- name: configure seafevents.conf
  template: src=seafevents.conf.j2 dest=/data/seafile/pro-data/seafevents.conf

- name: copy ceph.conf
  file: src=ceph.conf dest=/etc/ceph/ceph.conf

- name: copy client.seafile
  file: src=client.seafile dest=/etc/ceph/client.seafile
