# This playbook installs dependency packages for the seafile nodes

- name: Install node dependencies
  apt: name={{ item }} state=present
  with_items:
    - python2.7
    - python-setuptools
    - python-imaging
    - python-mysqldb
    - python-memcache
    - python-flup
    - libnss3
    - rsync
