# cluster initialization

- fail: msg="force_install not given. Run with -e force_install=true for a fresh install. THIS WILL REMOVE ALL CONTENTS from {{ seafile_base_dir }}"
  when: not force_install|default(False)

# wipe existing stuff for a clean start
- name: "remove existing {{ seafile_base_dir }}"
  file: name={{ seafile_base_dir }} state=absent

- name: "create {{ seafile_base_dir }}"
  file: name={{ seafile_base_dir }} state=directory

# unarchive installer
- name: extract seafile
  unarchive: >
    src="files/{{ installer_archive }}"
    dest="{{ seafile_base_dir }}"

# run install module
- name: init seafile master install
  seafile-init: >
    path="{{ seafile_base_dir }}"
    subdir="seafile-pro-server-{{ seafile_version }}"
    seafile_mysql_user="{{ db_user }}"
    seafile_mysql_password="{{ db_pw }}"
    mysql_host="{{ db_server }}"
    mysql_port="{{ db_port }}"
    ccnet_db_name="{{ db_ccnet }}"
    seafile_db_name="{{ db_seafile }}"
    seahub_db_name="{{ db_seahub }}"
