# This playbook installs packages for the seafile nodes

#- name: add nameserver
#  shell: echo "nameserver 141.20.1.3" >> /etc/resolv.conf

- name: Install python2.7
  apt: name=python2.7 state=present

- name: Install python-setuptools
  apt: name=python-setuptools state=present

- name: Install python-imaging
  apt: name=python-imaging state=present

- name: Install python-mysqldb
  apt: name=python-mysqldb state=present

- name: Install python-flup
  apt: name=python-flup state=present

- name: Install pip
  easy_install: name=pip

- name: Install boto via pip
  pip: name=boto

- name: Install nginx
  apt: name=nginx state=present

- name: Install memcached
  apt: name=memcached state=present

- name: create /data/seafile
  file: name=/data/seafile state=directory

- name: copy current seafile blob
  unarchive: src=seafile-current.tgz dest=/data/seafile
  tags: unarchive

- name: copy seafile license
  file: src=seafile-license.txt dest=/data/seafile/
