# This playbook contains all plays for the seafile nodes.

# dependencies for all seafile nodes
- include: dependencies.yml
  tags: install

# configure ceph
- include: ceph.yml

# configure nginx
- include: nginx.yml
  when: webserver == "nginx"

# configure Apache
- include: apache.yml
  when: webserver == "apache"

# startup config
- include: startup.yml

# configure golden image / master
- include: master.yml
  tags: master
  when: '"master" in group_names'

# sync clones
- include: clones.yml
  tags: clones
  when: 'not "master" in group_names'

# needed for init scripts to work
- name: make sure log directory exists
  file: path="{{ seafile_base_dir }}/logs" state=directory

- name: start cluster
  service: name=seafile-server state=started
