seahub_disable_throttling: no
ssl_nodes: no
# decrypt ssl at loadbalancer
ssl_dec_loadbalancer: yes
webserver: "apache"
use_shibboleth: no
use_ldap: no
email_replace_from_email: False
email_add_reply_to_header: False

#password
#password options. set true to use
pw_options: False
pw_repo_min_length: 8
pw_user_min_length: 6
pw_strength_level: 3
pw_user_strong_password_required: False

#thumbnail options
thumbnail_options: True
thumbnail_root: "{{ seafile_base_dir }}/seahub-data/thumbnail/thumb/" 
thumbnail_extension: png
thumbnail_default_size: 24
thumbnail_preview_default_size: 100

#session options
session_cookie_age: "60 * 60 * 24 * 7 * 2"
session_save_every_request: False
session_expire_at_browser_close: False
session_force_server_crypto: True

#ccnet.conf
ccnet_general_user_name: filesync
ccnet_client_port: 13419

#seafile.conf
seafile_network_port: 12001
seafile_fileserver_port: 8082

# language / location
time_zone: Europe/Berlin
lang_code: en

# background node settings
soffice_home: "soffice-home"

# configstack settings
restart_seafile_on_changes: True

# GUI settings
show_traffic: True
share_link_password_min_length: 8
enable_resumable_fileupload: False

# internal settings
fastcgi_timeout: 60

# backends
block_backend_name: ceph
commit_backend_name: ceph
fs_backend_name: ceph
# ceph backend
ceph_config: /etc/ceph/ceph.conf
ceph_client_id: seafile
ceph_pool_block: seafile-blocks
ceph_pool_commit: seafile-commits
ceph_pool_fs: seafile-fs
# s3 backend
s3_bucket_block: my-block-objects
s3_bucket_commit: my-commit-objects
s3_bucket_fs: my-fs-objects
s3_sigv4: False
