- name: Reload nginx
  shell: nginx -s reload
- name: Restart apache
  shell: service apache2 restart
- name: Restart shibd
  service: name=shibd state=restarted
  when: use_shibboleth
- name: Restart seafile
  service: name=seafile-server state=restarted
  when: restart_seafile_on_changes
