# install and configure memcached

- name: Install memcached
  apt: name=memcached state=present

- name: Configure memcached.conf
  template: src=memcached.conf.j2 dest=/etc/memcached.conf
  notify:
  - Restart memcached
